package com.analytics.poc.utils;

public class MyConstants {

    public interface SuperHeroInfo {

        String M_SPIDERMAN = "Spider-Man has spider-like abilities including superhuman strength and the ability to cling to most surfaces. He is also extremely agile and has amazing reflexes. Spider-Man also has a, “spider sense,” that warns him of impending danger.\n" +
                "\n" +
                "\n" +
                "Spider-Man has supplemented his powers with technology. Being a brilliant chemist and scientist, Peter has made web-slingers, bracelets that shoot out a sticky webbing, allowing him to swing from building to building and ensnare opponents. He has also developed stingers that shoot powerful energy blasts that can stun foes.\n" +
                "\n" +
                "In the recent storyline, Spider-Man has been reborn with even stronger abilities. He has the ability to see in the dark, enhanced senses, and can feel the vibrations through his webbing. In addition to this, the new, “Iron Spidey,” suit has enhanced his strength further and gives protection from damage. Recently, however, he has gotten rid of the suit and returned to the classic costume.";

        String M_HULK = "When Bruce Banner changes into the Hulk, he becomes an unstoppable beast of near unlimited strength, power, and destruction.\n" +
                "\n" +
                "\n" +
                "The Hulk’s strength is probably the greatest in the Marvel universe, with many foes falling to his thunderous attacks. The Hulk is also able to leap great distances traveling for miles before bounding upwards again.\n" +
                "\n" +
                "For his size, the Hulk is incredibly fast and can run great distances at extreme speeds. He generally travels by jumping as described above though. The hulk is also highly resistant to damage, being near impervious to most forms of damage. Very little has been known to faze the Hulk, except those of the same power level as the Hulk such as The Thing, Thor, Abomination, and others.\n" +
                "\n" +
                "Even when the Hulk is damaged, he heals quickly, and his endurance makes him an untiring creature capable of immense destruction. The Hulk is truly a marvel, both in his capability to defeat any enemy that would get in his way and as a being capable of destroying much that mankind has worked so hard to create.";

        String M_IRONMAN = "Anthony \"Tony\" Stark was born to Howard Anthony Stark and Maria Collins Carbonell Stark, owners of the prominent US firm, Stark Industries. As a boy, Tony was fascinated with building and controlling machines. At the age of 15 Tony entered the undergraduate electrical engineering program at the Massachusetts Institute of Technology (MIT), and graduated with two master’s degrees by age 19. Tony went to work for Stark Industries, but showed more interest in living a reckless playboy lifestyle than using his engineering skills. At the age of 21, Tony inherited Stark Enterprises when his parents were killed in a car accident secretly orchestrated by rival corporation Republic Oil (later ROXXON). Still lacking in business acumen, Tony promoted secretary Virginia \"Pepper\" Potts to be his executive assistant and left the majority of his workload on her so that he could avoid what he saw as a burden.\n" +
                "\n" +
                "Tony personally attended a field test of his military hardware at one of his international plants; however, soon after his arrival Stark’s party was attacked by a gang of terrorists led by the Sin-Cong revolutionary Wong Chu. During the skirmish, a land mine went off and lodged a piece of shrapnel near Tony’s heart. Taken back to Wong-Chu’s camp, Tony shared a cell with Professor Ho Yinsen, a world-famous physicist. Wong-Chu demanded that the two scientists develop advanced weaponry for his forces. Knowing that he could not live long with the shrapnel so close to his heart, Tony proposed that he and Yinsen devote their gifts to creating one of the battlesuits he had been developing, equipped with a magnetic field generator to prevent the shrapnel from reaching his heart. The armor they created became the first true Iron Man armor and was equipped with crude magnetic weaponry for defense. While the armor’s battery was being powered, some of Wong-Chu’s men attempted to break in on the proceedings. Yinsen went to create a diversion and was shot to death by Wong-Chu’s men. When the battery had finished charging, Tony went into battle as Iron Man and tore Wong-Chu’s camp apart. He eventually returned to the USA with the aid of US Marine James \"Rhodey\" Rhodes. Tony offered Rhodey a job with his company should he ever need one.\n" +
                "At first, Tony found his new life a torment; his armor’s chest plate had to be worn constantly and required frequent recharging. He kept the armor a secret from everyone, including his fiancée, Joanna Nivena. Turning suicidal and drinking heavily, Tony was supported by Joanna, with whom he shared his secret identity. Joanna encouraged him to use his armor as a super hero, but ultimately called off the engagement knowing Tony would not be the family man she desired.\n" +
                "\n" +
                "Tony worked to improve the Iron Man armor and claimed Iron Man was Tony Stark's personal bodyguard to disguise his identity. Tony played a dual-role with the formation of theAvengers both as the sponsor and, as Iron Man, as a founding member along with Thor, Ant-Man (Henry Pym), the Wasp (Janet van Dyne), and the Hulk. While pursuing Namor the Sub-Mariner, Iron Man came across the comatose body of Captain America (Steve Rogers) Rogers), the famous World War II super hero, preserved on ice. Revived, Captain America joined the Avengers and became an important teammate and friend to Tony. Later, Tony helped establish the international super-spy agency SHIELD to combat terrorist threats.\n" +
                "\n" +
                "\n" +
                "\n" +
                "";

        String M_DAREDEVIL = "Abandoned by his mother, Matt Murdock was raised by his father, boxer \"Battling Jack\" Murdock, in Hell's Kitchen. Realizing that rules were needed to prevent people from behaving badly, young Matt decided to study law; however, when he saved a man from an oncoming truck, it spilled a radioactive cargo that rendered Matt blind while enhancing his remaining senses. Under the harsh tutelage of blind martial arts master Stick, Matt mastered his heightened senses and became a formidable fighter. He also attended Columbia University Law School alongside his best friend, Franklin \"Foggy\" Nelson; but before Matt earned his Juris Doctorate degree, his father was murdered by agents of the Fixer (Roscoe Sweeny) for refusing to throw a fight. Enraged when the legal system failed to bring the Fixer to justice, Matt donned a costume made from his father's boxing robe and went into action as \"Daredevil,\" savagely beating his father's killers and frightening the Fixer himself to death. Establishing a small New York law firm with Foggy, Matt vowed to serve the law as Matt Murdock and to fight evils beyond the law's reach as Daredevil. Over the years, he has fought many super-criminals, including Mister Fear, Stilt-Man, Gladiator, Purple Man and Jester (Jonathan Powers), as well as crime lords such as the Kingpin and the Owl. He has loved and fought alongside both the Black Widow and Elektra.\n" +
                "Although Daredevil and the Punisher both fight crime, they often clash over the Punisher's lethal tactics. During an early encounter, Daredevil shot the Punisher to prevent him from killing drug-dealer Peter \"Hogman\" Grunter. Since then, Daredevil has worked with the Punisher when necessary, but has also attempted to bring him to justice. Daredevil formed the \"Marvel Knights\" to apprehend the Punisher, who escaped police custody thereafter. Later, Daredevil teamed with Spider-Man and Wolverine in a failed attempt to take down the Punisher, who told Daredevil that the only way to stop him was to kill him.\n" +
                "\n" +
                "Recently, Daredevil's secret identity was exposed by a tabloid and he definitively defeated the Kingpin in public, declaring himself New York's new kingpin. To avoid disbarment, Murdock has been forced to publicly and legally deny his dual identity, though the public remains unconvinced. He was incarcerated by the FBI which had been publicly embarrassed by Murdock and placed in a population comprised of many of his enemies in the hope that Murdock would be killed while in prison. Murdock, aided by the Punisher, escaped shortly thereafter.\n" +
                "\n" +
                "";

        String M_BLACKWIDOW = "Born circa 1928, Natalia \"Natasha\" Romanova was apparently orphaned as a child when she was trapped in a burning building during an early attack on Stalingrad by enemy forces. Ivan Petrovitch Bezukhov, a Soviet soldier, found Natasha in the inferno and rescued her. Although Ivan kept a close eye on Natasha as she grew, by the late 1930s she had attracted the attention of Soviet intelligence, which began her training. In 1941, she was almost brainwashed into serving the ninja clan the Hand, but was saved by Ivan, Logan (James Howlett, later Wolverine) and Captain America.\n" +
                "\n" +
                "Black Widow Program, a team of elite female sleeper agents. Among the Widow’s instructors was the Winter Soldier, formerly Captain America’s sidekick Bucky (James Barnes); Natasha studied as a ballerina to cover for her true occupation. The Soviet state eventually arranged for Natasha to marry Alexi Shostakov, a champion test pilot. After a few years of a happy marriage, the KGB faked Shostakov’s death in a rocket test; grief for Shostakov drove Natasha’s resolve deeper and she continued her education with the Red Room Academy, finally being appointed the title of the Black Widow.\n" +
                "\n" +
                "";

        String D_BATMAN = "A wealthy philanthropist, Thomas Wayne, his wife, Martha, and their 8 year-old son, Bruce Wayne, were coming out of a movie theater at 10:47 p.m. As they stepped onto Park Row (now called Crime Alley), a thug named Joe Chill armed with a gun approached them from the shadows to steal the pearl necklace Martha was wearing. Thomas, moving in to protect his wife, was shot by Chill, causing Martha to scream. Chill then shot her, while shouting, \"this'll shut you up!\". Bruce, traumatized by the deaths of his parents, would never be the same again. Afterward, Bruce was raised by his wise and loyal butler, Alfred Pennyworth, and inherited his family's vast fortune as well as his father's company, Wayne Enterprises. Standing at his parents' gravestones, Bruce made a solemn oath to avenge their deaths.\n" +
                "\n" +
                "Despite fiscal security, happiness eluded Bruce. Young Bruce was comforted by Dr. Leslie Thompkins, who helped him to mourn his parents and find a purpose in life. At age fourteen, Bruce started a twelve year walkabout around the world seeking experts in many fields, training himself mentally and physically. From an academic standpoint, he studied at Cambridge in England, the Sorbonne in France, and other famous European universities. A Frenchman named Henri Ducard taught him man-hunting, a ninja named Kirigi taught him stealth, an African bushman trained him in the art of the hunt, and Nepalese monks taught him healing.\n" +
                "\n" +
                "Bruce returned to Gotham City, where he became a vigilante. But despite all his honed skills, he knew something was missing. Bruce believed criminals to be a \"superstitious and cowardly lot,\" and in order to rid Gotham of evil, he needed to reinvent himself to become a terrifying symbol that would strike fear into the hearts of criminals. While in his father's study, a large bat crashed through the window. Bruce saw this as an omen and recalled his fear of bats as a child. This would be his symbol; the Bat would strike terror into the Gotham underworld. Using his vast wealth, Bruce designed a costume and state of the art equipment, thus beginning a difficult double life: by day, he would be the billionaire playboy and businessman, Bruce Wayne, and by night, he was The Batman.";

        String D_WONDERWOMAN = "Diana is the daughter of Queen Hippolyta, the first child born on Paradise Island in the three thousand year history that the immortal Amazons lived there. The Amazons had been created around 1200 B.C. when the Greek goddesses drew forth the souls of all women who had been murdered by men and placed them on the island. One soul was held back from creation, the one that would be born as Diana. That soul originally belonged to the unborn daughter of the first woman murdered by a man (whom Hippolyta was the reincarnation of). In the late 20th Century, Hippolyta was instructed to mold some clay from the shores of Paradise Island into the form of a baby girl. Six members of the Greek Pantheon then bonded the soul to the clay, giving it life. Each of the six also granted Diana a gift: Demeter, great strength; Athena, wisdom and courage; Artemis, a hunter's heart and a communion with animals; Aphrodite, beauty and a loving heart; Hestia, sisterhood with fire; Hermes, speed and the power of flight. Diana grew up surrounded by a legion of sisters and mothers. When she was a young woman, the gods decreed that the Amazons must send an emissary into Man's World. Queen Hippolyta ordered a contest to be held, but forbade Diana from participating. Diana disobeyed and did so anyway in disguise, easily winning the contest and being named the Amazon's champion. She was given a uniform fashioned from the standard of someone who had visited the island a few decades earlier.";

        String D_SUPERMAN = "The most recognized superhero in pop culture, Superman has been elevated to mythic folkhero status. Rocketed to Earth from the dying planet Krypton, baby Kal-El was found by a farming couple who named the boy Clark Kent and raised him as their own. Discovering his enormous powers, they instilled in him strong moral values—and inspired him to become a hero.\n" +
                "\n" +
                "Superman has super-everything—strength, speed, flight, invulnerability as well as his renowned X-ray and heat vision. The most powerful being on the planet, his amazing abilities are also a melancholy reminder of how different he is from the people he’s dedicated to protect. \n" +
                "\n" +
                "A universal icon, Superman means different things to the many diverse people he inspires: He’s an alien; an immigrant from a faraway land just looking to help; a country boy fighting the never-ending battle for truth and justice. And recent comics have truly spotlighted his role as the people’s hero: Following a neophyte Man of Steel still learning his powers’ limits, Superman fights the evil corporate tycoons and corrupt one-percenters that have overwhelmed the establishment. ";

        String D_GREENARROW = "What was the last thing you took home from an island getaway? A tacky souvenir? A great tan? More boring slideshows than you have friends to show?\n" +
                "\n" +
                "Spoiled billionaire Oliver Queen came home with an entirely different personality—and a newfound purpose in life. Completely self-absorbed and never caring about anything but himself, Queen was on a leisurely sailing trip when his assistant betrayed him, leaving him for dead on a desolate remote island. Stranded, he survived by, amongst other things, mastering a bow and arrow. When he eventually discovered the primitive locals that shared the island with him, he uncovered a large conglomerate sadistically exploiting and enslaving them. Ollie used his new skills of survival and archery to lead a rebellion— only to realize how similar his opponents were to the man he used to be.\n" +
                "\n" +
                "Returning to civilization only meant more opportunities to watch greed and corruption strangle Joe and Jane Average. Outfitting himself with arrows that shoot tear gas, smoke, nets, and more, Green Arrow has a trick shot for every obstacle. A modern-day Robin Hood, he constantly fights for the little guy as a crusading symbol for revolution. And his days on that island, filled with sweat, blood, and desperation, are a testament to what it takes for someone to answer that wake-up call, change their ways, and fly straight.\n" +
                "\n" +
                "As straight as an arrow.";

        String D_FLASH = "Young Barry Allen’s life stopped the minute his mother was murdered. The true killer never found, its mystery obsessed Barry, driving him to become a forensic scientist. Consumed by his work, he spent his life chained to his desk, solving every case that flew across it. But when a freak lightning bolt hits a nearby shelf in his lab, Barry receives super-speed, becoming the Flash. Now, he’ll race up buildings, across oceans, and around the world to get his man—while getting introduced to a world so much bigger than his old life of microscopes and cold cases.\n" +
                "\n" +
                "Able to run at near light-speeds, his powers provide the ultimate caffeine kick: He can run up buildings, move so swiftly he phases through objects, create sonic booms with the snap of his fingers—and never need to order delivery. Despite his speed, Barry can become so obsessed with crime-solving he can still lose track of everything else around him, leaving the fastest man alive constantly running a minute behind.";

    }

    public interface PrefrenceKeys {
        String PREF_IS_OTP_RECEIVED = "prefOtpReceived";
        String PREF_SET_PHONE = "prefPhoneNumber";
    }
}
